telegram:
    bot:
        username: pet_professor_bot
        token: 8065296727:AAH8B6pJIuuy7yY52paTe2wOk1qxGDGFy2s

spring:
    datasource:
        url: jdbc:mysql://35.187.253.64:3306/petoria_database?useSSL=false&serverTimezone=UTC
        username: qqy
        password: qqy1999815
        driver-class-name: com.mysql.cj.jdbc.Driver

    mybatis:
        mapper-locations: classpath:mapper/*.xml
        type-aliases-package: nus.iss.ais.petoria.model
    kafka:
        bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
        consumer:
            group-id: telegram-bot-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: '*' # Trust all packages

        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
